version: '3'
services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - net
  
  torchserve:
    container_name: torchserve
    image: pytorch/torchserve:latest
    command: ["torchserve", "--start", "--ncs", "--model-store", "model_store", "--models", "fasterrcnn_resnet50.mar"]
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./backend/model_store:/home/model-server/model_store 
      - ./backend/logs:/home/model-server/logs
    networks:
      - net

networks:
  net:
    driver: bridge
